base: base_link
left_front:
  - FL_hip
  - FL_upper_leg
  - FL_lower_leg
  - FL_toe

right_front:
  - FR_hip
  - FR_upper_leg
  - FR_lower_leg
  - FR_toe

left_hind:
  - RL_hip
  - RL_upper_leg
  - RL_lower_leg
  - RL_toe

right_hind:
  - RR_hip
  - RR_upper_leg
  - RR_lower_leg
  - RR_toe