"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - LF_HIP_JOINT
          - LF_THIGH_JOINT
          - LF_THIGH_FOOT_JOINT
          - RF_HIP_JOINT
          - RF_THIGH_JOINT
          - RF_THIGH_FOOT_JOINT
          - LH_HIP_JOINT
          - LH_THIGH_JOINT
          - LH_THIGH_FOOT_JOINT
          - RH_HIP_JOINT
          - RH_THIGH_JOINT
          - RH_THIGH_FOOT_JOINT

      gains:
        LF_HIP_JOINT : {p: 180, d: 0.9, i: 20}
        LF_THIGH_JOINT : {p: 180, d: 0.9, i: 20}
        LF_THIGH_FOOT_JOINT : {p: 180, d: 0.9, i: 20}
        RF_HIP_JOINT : {p: 180, d: 0.9, i: 20}
        RF_THIGH_JOINT : {p: 180, d: 0.9, i: 20}
        RF_THIGH_FOOT_JOINT : {p: 180, d: 0.9, i: 20}
        LH_HIP_JOINT : {p: 180, d: 0.9, i: 20}
        LH_THIGH_JOINT : {p: 180, d: 0.9, i: 20}
        LH_THIGH_FOOT_JOINT : {p: 180, d: 0.9, i: 20}
        RH_HIP_JOINT : {p: 180, d: 0.9, i: 20}
        RH_THIGH_JOINT : {p: 180, d: 0.9, i: 20}
        RH_THIGH_FOOT_JOINT : {p: 180, d: 0.9, i: 20}
