left_front:
  - base_link_FL_hip
  - FL_hip_FL_upper_leg
  - FL_upper_leg_FL_lower_leg
  - FL_lower_leg_FL_toe

right_front:
  - base_link_FR_hip
  - FR_hip_FR_upper_leg
  - FR_upper_leg_FR_lower_leg
  - FR_lower_leg_FR_toe

left_hind:
  - base_link_RL_hip
  - RL_hip_RL_upper_leg
  - RL_upper_leg_RL_lower_leg
  - RL_lower_leg_RL_toe

right_hind:
  - base_link_RR_hip
  - RR_hip_RR_upper_leg
  - RR_upper_leg_RR_lower_leg
  - RR_lower_leg_RR_toe