"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - base_link_FL_hip
          - FL_hip_FL_upper_leg
          - FL_upper_leg_FL_lower_leg
          - base_link_FR_hip
          - FR_hip_FR_upper_leg
          - FR_upper_leg_FR_lower_leg
          - base_link_RL_hip
          - RL_hip_RL_upper_leg
          - RL_upper_leg_RL_lower_leg
          - base_link_RR_hip
          - RR_hip_RR_upper_leg
          - RR_upper_leg_RR_lower_leg

      gains:
        base_link_FL_hip : {p: 100, d: 0.00000001, i: 0.5}
        FL_hip_FL_upper_leg : {p: 50, d: 0.0000001, i: 0.2}
        FL_upper_leg_FL_lower_leg : {p: 10, d: 0.00000001, i: 0.1}
        base_link_FR_hip : {p: 100, d: 0.00000001, i: 0.5}
        FR_hip_FR_upper_leg : {p: 50, d: 0.0000001, i: 0.2}
        FR_upper_leg_FR_lower_leg : {p: 10, d: 0.00000001, i: 0.1}
        base_link_RL_hip : {p: 100, d: 0.00000001, i: 0.5}
        RL_hip_RL_upper_leg : {p: 50, d: 0.0000001, i: 0.2}
        RL_upper_leg_RL_lower_leg : {p: 10, d: 0.00000001, i: 0.1}
        base_link_RR_hip : {p: 100, d: 0.00000001, i: 0.5}
        RR_hip_RR_upper_leg : {p: 50, d: 0.0000001, i: 0.2}
        RR_upper_leg_RR_lower_leg : {p: 10, d: 0.00000001, i: 0.1}

